ファイル整理
Gin-mmsm/image-calculator pull request #37
Opened 2020-09-17 16:51 UTC by Gin-mmsm

static folder の変更に伴う色々をやりました

2020-09-17 22:47 UTC, m-star18 commented
レビュー少し遅れます🙇‍♂️

2020-09-18 00:19 UTC, m-star18 requested changes
質問とリクエスト1つずつです🤲

2020-09-18 00:19 UTC, m-star18 commented on src/__init__.py
> +app = Flask(__name__, static_folder='static/')
static_folderのデフォルト値は'static/'なので設定しなくても大丈夫です👍

2020-09-18 00:19 UTC, m-star18 commented on src/views.py
> +        file.save("src/" + filepath)
filepath = "src/static/assets/" + datetime.now().strftime("%Y%m%d%H%M%S") + ".png"
で良いと思ったのですが分けたのは理由がありますか、？

2020-09-18 00:47 UTC, Gin-mmsm commented on src/views.py
> +        file.save("src/" + filepath)
renderに渡すときに分けた後ろの方だけ渡さないとうまく行かなかったんだよね...

2020-09-18 01:56 UTC, m-star18 commented on src/views.py
> +        file.save("src/" + filepath)
なるほど！大丈夫だと思います👍

2020-09-18 01:57 UTC, m-star18 approved these changes

2020-09-18 01:57 UTC, merged